[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["data/**", "*.json", "public/**", "images/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
